# Generated by Django 3.0.1 on 2019-12-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_garrafa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oleao',
            name='user',
        ),
    ]
